name: Docker Image CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3


    - name: Create .env file
      uses: SpicyPizza/create-envfile@v2
      with:
        envkey_EMAIL_SERVER: "testytesty"

        file_name: .env.production

    - name: List the files
      run: |
        ls -alG
